// File generated by Antigravity (manually reconstructed from config files)
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you are free to add web config here if needed.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you are free to add macOS config here if needed.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
          'you are free to add windows config here if needed.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you are free to add linux config here if needed.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzrNtT66jYLiIOIOjar8u8BX4MZ-imKMM',
    appId: '1:135235820665:android:de94df406f764e52e388a8',
    messagingSenderId: '135235820665',
    projectId: 'gbatcar-62ea4',
    storageBucket: 'gbatcar-62ea4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfz2KZvzuInD9kEuXJqAOv1PSHLctcKWw',
    appId: '1:135235820665:ios:ea69d278d4ab2809e388a8',
    messagingSenderId: '135235820665',
    projectId: 'gbatcar-62ea4',
    storageBucket: 'gbatcar-62ea4.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );
}
